---
abstract: 'Text::Template with localized variables'
author:
  - 'Diab Jerius, C<< <djerius at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.59'
dynamic_config: '0'
generated_by: 'Module::Install version 1.12, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Template-LocalVars
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Package::Stash: '0'
  Storable: '0'
  Symbol: '0'
  Text::Template: '0'
  parent: '0'
  perl: v5.8.9
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-Template-LocalVars
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: http://bitbucket.org/djerius/text-template-localvars
version: '0.02'
